name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: test and build library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/fermium'
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
    - run: yarn build
  deploy:
    name: Deploy Storybook to Netlify
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/fermium'
        cache: 'yarn'
    - run: yarn install
    - run: yarn build-storybook
    - uses: nwtgck/actions-netlify@v1.2 
      with:
        publish-dir: './storybook-static'
        production-branch: main
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

